/*
 * Copyright 2014 Ankush Sachdeva
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package github.ankushsachdeva.emojicon.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class Nature {
    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromChars(":sunny:"),
            Emojicon.fromChars(":umbrella:"),
            Emojicon.fromChars(":cloud:"),
            Emojicon.fromChars(":snowflake:"),
            Emojicon.fromChars(":snowman:"),
            Emojicon.fromChars(":zap:"),
            Emojicon.fromChars(":cyclone:"),
            Emojicon.fromChars(":foggy:"),
            Emojicon.fromChars(":ocean:"),
            Emojicon.fromChars(":cat:"),
            Emojicon.fromChars(":dog:"),
            Emojicon.fromChars(":mouse:"),
            Emojicon.fromChars(":hamster:"),
            Emojicon.fromChars(":rabbit:"),
            Emojicon.fromChars(":wolf:"),
            Emojicon.fromChars(":frog:"),
            Emojicon.fromChars(":tiger:"),
            Emojicon.fromChars(":koala:"),
            Emojicon.fromChars(":bear:"),
            Emojicon.fromChars(":pig:"),
            Emojicon.fromChars(":pig_nose:"),
            Emojicon.fromChars(":cow:"),
            Emojicon.fromChars(":boar:"),
            Emojicon.fromChars(":monkey_face:"),
            Emojicon.fromChars(":monkey:"),
            Emojicon.fromChars(":horse:"),
            Emojicon.fromChars(":racehorse:"),
            Emojicon.fromChars(":camel:"),
            Emojicon.fromChars(":sheep:"),
            Emojicon.fromChars(":elephant:"),
            Emojicon.fromChars(":panda_face:"),
            Emojicon.fromChars(":snake:"),
            Emojicon.fromChars(":bird:"),
            Emojicon.fromChars(":baby_chick:"),
            Emojicon.fromChars(":hatched_chick:"),
            Emojicon.fromChars(":hatching_chick:"),
            Emojicon.fromChars(":chicken:"),
            Emojicon.fromChars(":penguin:"),
            Emojicon.fromChars(":turtle:"),
            Emojicon.fromChars(":bug:"),
            Emojicon.fromChars(":honeybee:"),
            Emojicon.fromChars(":ant:"),
            Emojicon.fromChars(":beetle:"),
            Emojicon.fromChars(":snail:"),
            Emojicon.fromChars(":octopus:"),
            Emojicon.fromChars(":tropical_fish:"),
            Emojicon.fromChars(":fish:"),
            Emojicon.fromChars(":whale:"),
            Emojicon.fromChars(":whale2:"),
            Emojicon.fromChars(":dolphin:"),
            Emojicon.fromChars(":cow2:"),
            Emojicon.fromChars(":ram:"),
            Emojicon.fromChars(":rat:"),
            Emojicon.fromChars(":water_buffalo:"),
            Emojicon.fromChars(":tiger2:"),
            Emojicon.fromChars(":rabbit2:"),
            Emojicon.fromChars(":dragon:"),
            Emojicon.fromChars(":goat:"),
            Emojicon.fromChars(":rooster:"),
            Emojicon.fromChars(":dog2:"),
            Emojicon.fromChars(":pig2:"),
            Emojicon.fromChars(":mouse2:"),
            Emojicon.fromChars(":ox:"),
            Emojicon.fromChars(":dragon_face:"),
            Emojicon.fromChars(":blowfish:"),
            Emojicon.fromChars(":crocodile:"),
            Emojicon.fromChars(":dromedary_camel:"),
            Emojicon.fromChars(":leopard:"),
            Emojicon.fromChars(":cat2:"),
            Emojicon.fromChars(":poodle:"),
            Emojicon.fromChars(":paw_prints:"),
            Emojicon.fromChars(":bouquet:"),
            Emojicon.fromChars(":cherry_blossom:"),
            Emojicon.fromChars(":tulip:"),
            Emojicon.fromChars(":four_leaf_clover:"),
            Emojicon.fromChars(":rose:"),
            Emojicon.fromChars(":sunflower:"),
            Emojicon.fromChars(":hibiscus:"),
            Emojicon.fromChars(":maple_leaf:"),
            Emojicon.fromChars(":leaves:"),
            Emojicon.fromChars(":fallen_leaf:"),
            Emojicon.fromChars(":herb:"),
            Emojicon.fromChars(":mushroom:"),
            Emojicon.fromChars(":cactus:"),
            Emojicon.fromChars(":palm_tree:"),
            Emojicon.fromChars(":evergreen_tree:"),
            Emojicon.fromChars(":deciduous_tree:"),
            Emojicon.fromChars(":chestnut:"),
            Emojicon.fromChars(":seedling:"),
            Emojicon.fromChars(":blossom:"),
            Emojicon.fromChars(":ear_of_rice:"),
            Emojicon.fromChars(":shell:"),
            Emojicon.fromChars(":globe_with_meridians:"),
            Emojicon.fromChars(":sun_with_face:"),
            Emojicon.fromChars(":full_moon_with_face:"),
            Emojicon.fromChars(":new_moon_with_face:"),
            Emojicon.fromChars(":new_moon:"),
            Emojicon.fromChars(":waxing_crescent_moon:"),
            Emojicon.fromChars(":first_quarter_moon:"),
            Emojicon.fromChars(":waxing_gibbous_moon:"),
            Emojicon.fromChars(":full_moon:"),
            Emojicon.fromChars(":waning_gibbous_moon:"),
            Emojicon.fromChars(":last_quarter_moon:"),
            Emojicon.fromChars(":waning_crescent_moon:"),
            Emojicon.fromChars(":last_quarter_moon_with_face:"),
            Emojicon.fromChars(":first_quarter_moon_with_face:"),
            Emojicon.fromChars(":moon:"),
            Emojicon.fromChars(":earth_africa:"),
            Emojicon.fromChars(":earth_americas:"),
            Emojicon.fromChars(":earth_asia:"),
            Emojicon.fromChars(":volcano:"),
            Emojicon.fromChars(":milky_way:"),
            Emojicon.fromChars(":partly_sunny:"),
            Emojicon.fromChars(":octocat:"),
            Emojicon.fromChars(":squirrel:"),
    };
}
