/*
 * Copyright 2014 Ankush Sachdeva
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package github.ankushsachdeva.emojicon.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class Places {
    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromChars(":house:"),
            Emojicon.fromChars(":house_with_garden:"),
            Emojicon.fromChars(":school:"),
            Emojicon.fromChars(":office:"),
            Emojicon.fromChars(":post_office:"),
            Emojicon.fromChars(":hospital:"),
            Emojicon.fromChars(":bank:"),
            Emojicon.fromChars(":convenience_store:"),
            Emojicon.fromChars(":love_hotel:"),
            Emojicon.fromChars(":hotel:"),
            Emojicon.fromChars(":wedding:"),
            Emojicon.fromChars(":church:"),
            Emojicon.fromChars(":department_store:"),
            Emojicon.fromChars(":european_post_office:"),
            Emojicon.fromChars(":city_sunrise:"),
            Emojicon.fromChars(":city_sunset:"),
            Emojicon.fromChars(":japanese_castle:"),
            Emojicon.fromChars(":european_castle:"),
            Emojicon.fromChars(":tent:"),
            Emojicon.fromChars(":factory:"),
            Emojicon.fromChars(":tokyo_tower:"),
            Emojicon.fromChars(":japan:"),
            Emojicon.fromChars(":mount_fuji:"),
            Emojicon.fromChars(":sunrise_over_mountains:"),
            Emojicon.fromChars(":sunrise:"),
            Emojicon.fromChars(":stars:"),
            Emojicon.fromChars(":statue_of_liberty:"),
            Emojicon.fromChars(":bridge_at_night:"),
            Emojicon.fromChars(":carousel_horse:"),
            Emojicon.fromChars(":rainbow:"),
            Emojicon.fromChars(":ferris_wheel:"),
            Emojicon.fromChars(":fountain:"),
            Emojicon.fromChars(":roller_coaster:"),
            Emojicon.fromChars(":ship:"),
            Emojicon.fromChars(":speedboat:"),
            Emojicon.fromChars(":boat:"),
            Emojicon.fromChars(":sailboat:"),
            Emojicon.fromChars(":rowboat:"),
            Emojicon.fromChars(":anchor:"),
            Emojicon.fromChars(":rocket:"),
            Emojicon.fromChars(":airplane:"),
            Emojicon.fromChars(":helicopter:"),
            Emojicon.fromChars(":steam_locomotive:"),
            Emojicon.fromChars(":tram:"),
            Emojicon.fromChars(":mountain_railway:"),
            Emojicon.fromChars(":bike:"),
            Emojicon.fromChars(":aerial_tramway:"),
            Emojicon.fromChars(":suspension_railway:"),
            Emojicon.fromChars(":mountain_cableway:"),
            Emojicon.fromChars(":tractor:"),
            Emojicon.fromChars(":blue_car:"),
            Emojicon.fromChars(":oncoming_automobile:"),
            Emojicon.fromChars(":car:"),
            Emojicon.fromChars(":red_car:"),
            Emojicon.fromChars(":taxi:"),
            Emojicon.fromChars(":oncoming_taxi:"),
            Emojicon.fromChars(":articulated_lorry:"),
            Emojicon.fromChars(":bus:"),
            Emojicon.fromChars(":oncoming_bus:"),
            Emojicon.fromChars(":rotating_light:"),
            Emojicon.fromChars(":police_car:"),
            Emojicon.fromChars(":oncoming_police_car:"),
            Emojicon.fromChars(":fire_engine:"),
            Emojicon.fromChars(":ambulance:"),
            Emojicon.fromChars(":minibus:"),
            Emojicon.fromChars(":truck:"),
            Emojicon.fromChars(":train:"),
            Emojicon.fromChars(":station:"),
            Emojicon.fromChars(":train2:"),
            Emojicon.fromChars(":bullettrain_front:"),
            Emojicon.fromChars(":bullettrain_side:"),
            Emojicon.fromChars(":light_rail:"),
            Emojicon.fromChars(":monorail:"),
            Emojicon.fromChars(":railway_car:"),
            Emojicon.fromChars(":trolleybus:"),
            Emojicon.fromChars(":ticket:"),
            Emojicon.fromChars(":fuelpump:"),
            Emojicon.fromChars(":vertical_traffic_light:"),
            Emojicon.fromChars(":traffic_light:"),
            Emojicon.fromChars(":warning:"),
            Emojicon.fromChars(":construction:"),
            Emojicon.fromChars(":beginner:"),
            Emojicon.fromChars(":atm:"),
            Emojicon.fromChars(":slot_machine:"),
            Emojicon.fromChars(":busstop:"),
            Emojicon.fromChars(":barber:"),
            Emojicon.fromChars(":hotsprings:"),
            Emojicon.fromChars(":checkered_flag:"),
            Emojicon.fromChars(":crossed_flags:"),
            Emojicon.fromChars(":izakaya_lantern:"),
            Emojicon.fromChars(":moyai:"),
            Emojicon.fromChars(":circus_tent:"),
            Emojicon.fromChars(":performing_arts:"),
            Emojicon.fromChars(":round_pushpin:"),
            Emojicon.fromChars(":triangular_flag_on_post:"),
            //Emojicon.fromChars(":in:"),
            Emojicon.fromChars(":jp:"),
            Emojicon.fromChars(":kr:"),
            Emojicon.fromChars(":cn:"),
            Emojicon.fromChars(":us:"),
            Emojicon.fromChars(":fr:"),
            Emojicon.fromChars(":es:"),
            Emojicon.fromChars(":it:"),
            Emojicon.fromChars(":ru:"),
            Emojicon.fromChars(":gb:"),
            Emojicon.fromChars(":uk:"),
            Emojicon.fromChars(":de:"),
    };
}
